# Generated by Django 3.2 on 2021-04-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='topic',
        ),
    ]
