# Generated by Django 3.2 on 2021-04-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_topic_entry_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='blog',
        ),
    ]
